name: Build, Tag and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag_and_release:
    runs-on: windows-latest
    env:
      PYTHONIOENCODING: utf-8

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Extract version from merge commit
        id: extract_version
        shell: bash
        run: |
          MERGE_COMMIT=$(git log --merges -1 --pretty=format:"%s")
          echo "Merge commit message: $MERGE_COMMIT"
          if [[ "$MERGE_COMMIT" =~ release\/ver([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            VERSION="${BASH_REMATCH[1]}"
            echo "Extracted version: $VERSION"
            echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          else
            echo "No version extracted"
            exit 1
          fi

      - name: Create or update tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -f v${{ steps.extract_version.outputs.version }} $GITHUB_SHA
          git push origin -f v${{ steps.extract_version.outputs.version }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build project
        run: python build_release.py

      - name: Zip output
        run: |
          powershell Compress-Archive -Path dist/INFINITAS_Online_Battle/* -DestinationPath dist/INFINITAS_Online_Battle.zip

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.extract_version.outputs.version }}
          draft: true
          files: dist/INFINITAS_Online_Battle.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
